name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo, sqlite

    - name: Install Composer dependencies
      working-directory: Proyecto-Linces
      run: |
        composer install --no-progress --prefer-dist --optimize-autoloader --no-dev

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      working-directory: Proyecto-Linces
      run: npm install

    - name: Build assets
      working-directory: Proyecto-Linces
      run: npm run build

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
        rsync -avr --exclude='.git' --exclude='node_modules' --exclude='vendor' Proyecto-Linces/ $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH
        ssh $SERVER_USER@$SERVER_HOST "
          cd $DEPLOY_PATH
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          npm install
          npm run build
        "
