name: Proyecto Linces Build Laravel 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo, sqlite

    - name: Install Composer dependencies
      run: |
        cd Proyecto-Linces
        composer install --no-progress --prefer-dist --optimize-autoloader --no-dev

    - name: Verify Composer installation
      run: |
        cd Proyecto-Linces
        ls -la vendor/bin

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: |
        cd Proyecto-Linces
        npm install

    - name: Build assets
      run: |
        cd Proyecto-Linces
        npm run build

    - name: Run tests
      run: |
        cd Proyecto-Linces
        ./vendor/bin/phpunit
