name: PHP Composer -  Proyecto Linces

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo, sqlite

    - name: Validate composer.json and composer.lock
      working-directory: Proyecto-Linces
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: Proyecto-Linces/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      working-directory: Proyecto-Linces
      run: composer install --prefer-dist --no-progress

    - name: Run tests
      working-directory: Proyecto-Linces
      run: composer run-script test
